services:
  server:
    image: dmitrykruglov/notes.server:latest
    ports:
      - 3000:3000

  client:
    depends_on:
      - server
    image: dmitrykruglov/notes.client:latest
    ports:
      - 80:80
      - 443:443