name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix server
      - name: Lint
        run: npm run lint --prefix server
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix server
      - name: Test
        run: npm run test --prefix server
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix client
      - name: Lint
        run: npm run lint --prefix client
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix client
      - name: Test
        run: npm run test --prefix client
  build-server:
    needs: [lint-server, test-server]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: server/
          push: true
          tags: dmitrykruglov/notes.server:latest
  build-client:
    needs: [lint-client, test-client]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: client/
          push: true
          tags: dmitrykruglov/notes.client:latest
  deploy:
    needs: [build-server, build-client]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        options: |
          --verbose