name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix server
      - name: Lint
        run: npm run lint --prefix server
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix server
      - name: Test
        run: npm run test --prefix server
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix client
      - name: Lint
        run: npm run lint --prefix client
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci --prefix client
      - name: Test
        run: npm run test --prefix client